# Generated by Django 4.2.5 on 2023-10-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Comedy', 'Comedy'), ('Fantasy', 'Fantasy'), ('Romance', 'Romance')], default='Comedy', max_length=7),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
