# Generated by Django 4.2.5 on 2023-10-13 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_genre_movie_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='movie',
        ),
    ]
